### ISSUE TITLE
Malkin (neighborhood)?

### ISSUE THREAD

**Issue by cluel01** [chrsmrrs/k-gnn#10]
I'm currently trying to adapt your model for my work on GNNs but after reading the referenced paper, I wonder what exactly is the Malkin (am I right with the term neighborhood?) in contrast to the local neighborhood definition from your paper ? In your paper it is stated that you would use the local neighborhood for creating the subsets.

**Comment by chrsmrrs** [comment]
The Malkin neighborhood is defined in https://arxiv.org/abs/1107.0632, see also https://grlplus.github.io/papers/80.pdf.
