### ISSUE TITLE
Warning while pre_transform QM9 example

### ISSUE THREAD

**Issue by cluel01** [chrsmrrs/k-gnn#11]
Hello,

I'm testing your 1-2 QM9 example. Everything works well despite the fact that I get Warnings for each Data object while transforming them with the TwoMalkin Function. For every Data object I get the following warning:
`Warning: The number of elements in the out tensor of shape [105] is 105 which does not match the computed number of elements 780. Note that this may occur as a result of rounding error. The out tensor will be resized to a tensor of shape (780,). (operator() at /opt/conda/conda-bld/pytorch_1579022060824/work/aten/src/ATen/native/RangeFactories.cpp:170)`
Can you confirm the warning when running it in your environment or is this my fault?

**Comment by chrsmrrs** [comment]
Which version of PyG and Torch did you use?

**Comment by rusty1s** [comment]
I removed the warning in the current master, but it did not do any harm to the graph construction phase.
