### ISSUE TITLE
cpu/utils.h:27:10: error: reference to 'stack' is ambiguous

### ISSUE THREAD

**Issue by reBiocoder** [chrsmrrs/k-gnn#16]
i try to use this rep, but while i run `python steup.py install`,i get error:
```
cpu/utils.h:27:10: error: reference to 'stack' is ambiguous
```

**environment**
**os**: OS X 11.2.3

**c++ compiler**
```
clang version 11.1.0
Target: x86_64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /usr/local/Cellar/llvm/11.1.0/bin
``` 
Is it my software version problem? thanks!

**Comment by chrsmrrs** [comment]
Which Pytorch and which Geometric version did you use? The code is only tested under Linux.

**Comment by reBiocoder** [comment]
> Which Pytorch and which Geometric version did you use? The code is only tested under Linux.

thank you for your reply! My dependency version is as follows
------
**Pytorch version**: 1.8.0

**Pytorch Geometric version**:1.6.3

**torch_sparse**:0.6.9

**torch_scatter**:2.0.6

**torch_cluster**:1.5.9

******

Can you provide your version dependencies? thank you very much

**Comment by chrsmrrs** [comment]
As stated in the Readme it was developed for PyTorch Geometric 1.4 on a Linux system. We did not test the software for MacOS system.s
