### ISSUE TITLE
debug Import error

### ISSUE THREAD

**Issue by YJYTJ** [chrsmrrs/k-gnn#17]
When I debug using VS code, I find this problem. But I can run it successfully in terminal.
![image](https://user-images.githubusercontent.com/51269506/153349789-d04b3723-40ea-4031-a85f-d8dc421df249.png)
Could you please help me?

**Comment by rusty1s** [comment]
Thanks for reporting. Can you post your PyTorch version and any installation logs of `k_gnn`? There might have occurred some failures during installation.

**Comment by YJYTJ** [comment]
That is because I used the wrong version of Pytorch-geometric. Thank you!
