### ISSUE TITLE
segmentation error when calling 1-2-qm9.py

### ISSUE THREAD

**Issue by whoyouwith91** [chrsmrrs/k-gnn#5]
Hi, I was trying to train QM9 dataset using CPUs. However, it keeps showing there is asegmentation fault. I'm not sure where this problem comes from. Any hints? Thanks!

**Comment by rusty1s** [comment]
I cannot reproduce this issue. Do you know where the segmentation fault occurs?

**Comment by whoyouwith91** [comment]
> I cannot reproduce this issue. Do you know where the segmentation fault occurs?

It turned out that the Graph_cpu.TwoMalkin() consumes a lot of memory in the transforming process of data. Any way around? Thanks!

**Comment by whoyouwith91** [comment]
> I cannot reproduce this issue. Do you know where the segmentation fault occurs?
Actually, when I started from import, it threw me an error like below: 

>>> import k_gnn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/beegfs/dz1061/gcn/k-gnn/k_gnn/__init__.py", line 1, in <module>
    from graph_cpu import two_local, connected_two_local
ImportError: /scratch/dz1061/packages/envs/torch/lib/python3.7/site-packages/k_gnn-0.0.0-py3.7-linux-x86_64.egg/graph_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZTIN3c1021AutogradMetaInterfaceE

**Comment by whoyouwith91** [comment]
> I cannot reproduce this issue. Do you know where the segmentation fault occurs?

Never mind, I figured it out. Thanks anyway.

**Comment by rusty1s** [comment]
How did you resolve it?

**Comment by whoyouwith91** [comment]
> How did you resolve it?

Well, it was because the version of GCC compiler is too old. I first noticed that the graph-cpu module in your package is wrapped in PyTorch c++ extension, so I used a newer version to install the k-gnn from source.

**Comment by whoyouwith91** [comment]
Do you mind telling me the hyper parameters you used for the training of QM9 using 1-2-GNN model? Like the initial learning rate, decaying factor, and so on. Thanks so much.

**Comment by rusty1s** [comment]
We use the hyperparameters provided in the `1-2-qm9.py` script. Don't they work for you?

**Comment by whoyouwith91** [comment]
> We use the hyperparameters provided in the `1-2-qm9.py` script. Don't they work for you?

I trained the QM9 U0 (target is 7) for over 500 epochs, the result is as shown below: 
Epoch: 646, LR: 0.000010, Loss: 0.0000107, Validation MAE: 0.1383203, Test MAE: 0.1440089, Test MAE norm: 0.0035993

I think the training time is long enough, right? But Test MAE is not close to your result which is around 0.03.

**Comment by rusty1s** [comment]
This is weird, those are the hyperparameters we used in our experiments. I think that the update of the code base to the latest PyTorch version might have something do to with this. I will definitely look into it, although this might take some time. Sorry!

**Comment by whoyouwith91** [comment]
> This is weird, those are the hyperparameters we used in our experiments. I think that the update of the code base to the latest PyTorch version might have something do to with this. I will definitely look into it, although this might take some time. Sorry!

Hi, so did you figure it out? Is it because of the version or other things?
