### ISSUE TITLE
some questions about u paper

### ISSUE THREAD

**Issue by Jeff-0230** [chrsmrrs/k-gnn#6]
Hi, I'm very appreciate u for sharing the code & paper. 
Awesome ! 
I get some questions.

First, "We always used three layers for 1-GNN, and two layers for (local) 2-GNNand 3-GNN,all with a hidden-dimension size of 64. " why 64？ Based on empirical intuition or  experimental trial-and-error?Can I use other numbers instead of 64?

Second, why " |s∩t|=k-1 "? u just tell the existence of "k-1" . I wanna know the meaning of "k-1" in the design of N(s).

The last question is what the model learned through the training. Matrix？Parameter？I konw it is crazy , but i wanna visualize "it" the model learned.

**Comment by rusty1s** [comment]
Hi,

1. You can use other hidden dimensionalities. `64` is just what we found out worked out well across a number of experiments.

2. Two subsets are neighbors in `G^k` if their intersection holds exactly `k-1` elements.

3. The model learns a weight matrix for each layer, *e.g.*, `64x64` parameters, which is used to transform node features before aggregating them.
