### ISSUE TITLE
TypeError: expected Tensor as element 0 in argument 0, but got list

### ISSUE THREAD

**Issue by muhanzhang** [chrsmrrs/k-gnn#9]
Hello,

When running
https://github.com/chrsmrrs/k-gnn/blob/834c517be140767902a789a4f2697c3f22874a06/k_gnn/dataloader.py#L61
I encountered "TypeError: expected Tensor as element 0 in argument 0, but got list" error.

Should it be changed to 
keys = [x for x in batch.keys if x not in ['batch', 'batch_2', 'batch_3', 'name']]? The names are list of list of strings which cannot be used in torch.cat.

**Comment by rusty1s** [comment]
Yes, the `QM9` dataset got enhanced by `name`. You can either upgrade your PyG version or just remove it from the dataset:
```
dataset.data.name = None
```

**Comment by muhanzhang** [comment]
Thanks for the quick reply. Yes, since QM9 is enhanced with ``name``, should this k-gnn repository also be updated to accomodate the new ``name`` key?

**Comment by rusty1s** [comment]
Ah I see, the k-GNN `DataLoader` fails here. Yes, we should do this.

**Comment by rusty1s** [comment]
Should be fixed [here](https://github.com/chrsmrrs/k-gnn/blob/master/k_gnn/dataloader.py#L63).
